stages:
  - ğŸ”test

variables:
  MAVEN_OPTS: "-Dmaven.repo.local=./.m2/repository"

cache:
  paths:
    - ./.m2/

test::java:
  stage: ğŸ”test
  image: openjdk:11-jdk
  script:
    - apt-get update && apt-get -y install maven && apt-get clean
    - mvn $MAVEN_OPTS install

test::sonar:
  stage: ğŸ”test
  image: openjdk:11-jdk
  script:
    - apt-get update && apt-get -y install maven && apt-get clean
    - mvn $MAVEN_OPTS sonar:sonar

